/*
 * Automated Transpiled C++ Decision Tree Header for Microcontroller Feasibility Analysis
 * Reference Paper: iJOE (2026) — Subject-Specific PVC Detection Pipeline
 * Generated by: src/export_to_cpp.py
 * Target Record: MIT-BIH Patient 208 (Dual-Voting Consensus Feature Selection)
 * Evaluated Decision Tree Features: Post_RR, Pre_RR, Corr_Coeff
 * Projected RAM Footprint: < 3 KB (depth <= 8)
 * Projected Execution Latency: < 1 us branch traversal (peak ~20 us) on 240 MHz Xtensa LX6 core
 * Physiological Delay Buffer: Requires subsequent R-peak observation (~600 ms at resting heart rate)
 * Note: Retrospective offline study in Python; physical on-hardware deployment is designated as future work.
 */

#ifndef PVC_CLASSIFIER_H
#define PVC_CLASSIFIER_H

// BeatFeatures defines the feature buffer. Unused members (RR_Ratio, SAD,
// Hjorth_Activity, Peak_to_Peak, Steepness) are retained for feature extraction
// pipeline interface compatibility; classify_pvc_beat() evaluates Post_RR, Pre_RR, and Corr_Coeff.
struct BeatFeatures {
    float Pre_RR;
    float Post_RR;
    float RR_Ratio;
    float SAD;
    float Corr_Coeff;
    float Hjorth_Activity;
    float Peak_to_Peak;
    float Steepness;
};

// Returns 0 for Normal Sinus Beat ('N'), 1 for Premature Ventricular Contraction ('V')
inline int classify_pvc_beat(const BeatFeatures& f) {
    if (f.Post_RR <= 0.655556f) {
        if (f.Pre_RR <= 0.444444f) {
            return 1; // Ectopic Premature Beat (PVC)
        } else {
            return 0; // Normal Beat
        }
    } else {
        if (f.Corr_Coeff <= 0.825000f) {
            return 1; // Morphology Deviation (PVC)
        } else {
            return 0; // Normal Beat with pause
        }
    }
}

#endif // PVC_CLASSIFIER_H